# Use official Node.js image
FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY client/ .

# Build the React app for production
RUN npm run build

# Expose port for the React app
EXPOSE 3000

# Serve the React app with a static server
CMD ["npm", "start"]
