version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: npm start

  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
    command: npm run dev
