# Use official Node.js image
FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY api/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY api/ .

# Expose the API port
EXPOSE 8000

# Command to run the server
CMD ["npm", "run", "dev"]
